apiVersion: 1

datasources:
  - name: InfluxDB TRIA
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: tria
      defaultBucket: tria_events
    secureJsonData:
      token: tria-token-2026
    isDefault: true
    editable: true